### ISSUE TITLE
Cannot see Grid Voltage?

### ISSUE THREAD

**Issue by Sage222** [TimSoethout/goodwe-sems-home-assistant#126]
Hi - is there anyway to see Grid Voltage?  It is listed on the SEMS portal - though i cant see it in your plugin? thanks very much

**Comment by TimSoethout** [comment]
Hi, check the attributes of the power sensor.

In a future update I plan to make it a separate sensor. For now you can create a template sensor, see the readme.

15 May 2025 09:36:13 Sage ***@***.***>:

**Comment by Sage222** [comment]
thanks for the response will check it out!

**Comment by TimSoethout** [comment]
Indeed, you can try 7.2.0 nonbeta.

19 Jun 2025 10:32:27 Sage ***@***.***>:

**Comment by Sage222** [comment]
not that i can see.. only the entities above.  though its reported on the SEMS portala and the app .. so it is available.

![Image](https://github.com/user-attachments/assets/063fc187-61c7-4253-b4cb-fe51f80c47ba)

**Comment by TimSoethout** [comment]
The entity should contain attributes such as:
https://github.com/TimSoethout/goodwe-sems-home-assistant/raw/master/images/sems-details.webp
from the readme.

**Comment by VidarParry** [comment]
@Sage222 Thank you. This is what I was hoping to extract as well.

However, I can't get the sensor to appear using your code.

In configuration.yaml I'm using:
```
sensor:
  - name: "Inverter Voltage"
    unique_id: inverter_voltage_sensor
    unit_of_measurement: "V"
    state: "{{ state_attr('sensor.inverter_XXXXXXXXX', 'vac1') }}"
```

I can't see the vac1 sensor in the available entities for the inverter, nor can I add it (vac1).

Appreciate any guidance (sorry - I'm new to HA and YAML).
Cheers...Steve

**Comment by Sage222** [comment]
use chatgpt it will step you through it. essentially need to go to Developer Settings > States > and find the Inverter device and Attribute/Property that you want.  Then you need to edit your configuration.yaml file to add a new Sensor for that attribute.  Then reboot HA and it should appear.  Chatgpt will step you through it better than i can :)

**Comment by VidarParry** [comment]
Thanks Sage222. ChatGPT nor CoPilot helped - I was following that process already.

Found the issue - in my setup (don't know why) the vac1 is an attribute of sensor.inverter_XXXXXXXXXXX_power. So what I ended up with was:

```
template:
  - sensor:
    - name: "SEMS Inverter Grid Voltage"
      unique_id: sems_inverter_grid_voltage_sensor
      unit_of_measurement: "V"
      state: "{{ state_attr('sensor.inverter_XXXXXXXXXXX_power', 'vac1') }}"
```

All working now.

Cheers
...Steve
