### ISSUE TITLE
Energy Monitor Home Assistant 

### ISSUE THREAD

**Issue by Alfagek** [TimSoethout/goodwe-sems-home-assistant#37]
Hey Tim,

First a big thank you for making this. I’m using it almost a year and it’s working great. 

But I have a question. Home Assistant has a new Energy monitor (2021.8). And I’m using your setup to get all things that I want in Home Assistant. But i don’t see my power return in this Energy monitor. I do have it as a entity. 

Do you know how I can get this now to use it in the new Home Assistant Energy Monitor. 
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Thanks in advance,
Marco

**Comment by kolossboss** [comment]
Hi have the same question. Its all sensors are not shown in the energy configuration panel.

I think I have to include a last_reset property. But I'm not sure how to do this.

**Comment by Alfagek** [comment]
Thanks for trying @kolossboss . There should probably more people who have this “problem” we will wait (and Google in the mean time)

**Comment by TimSoethout** [comment]
Yes let's try to get this working. Not sure about the reset time, but maybe
the API also shows kWh this year and we can use start of current year for
this.

**Comment by kolossboss** [comment]
Hi,
I now created a template sensor with `total_buy`

```
- platform: template
  sensors:
    pv_buy_total:
      value_template: "{{ states.sensor.sems_portal.attributes.total_buy }}"
      unit_of_measurement: "kWh"
      friendly_name: "PV kWh gekauft Total"
```

An created a Utility Meter Sensor and cycle daily

```
utility_meter:
  energy_buy_daily_test:
    source: sensor.pv_buy_total
    cycle: daily
```

Added a few missing attributes to `sensor.energy_buy_daily_test` in the customize.yaml

```
sensor.energy_buy_daily_test:
  unit_of_measurement: kWh
  device_class: energy
```

Now the sensor is detected by the Energy Management configuration. But I'm not sure if its working, because I'm not receiving any data at this moment (house ins running on battery)
