### ISSUE TITLE
Sems Portal

### ISSUE THREAD

**Issue by davidsonimagerygmailcom** [TimSoethout/goodwe-sems-home-assistant#94]

**Comment by davidsonimagerygmailcom** [comment]
So sorry for the edits, git hub "post" button wasn't functonal (known issue with github) and I was trying to get post to work with less text (which worked).
Screenies ;
![Capture](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/633fc33a-6557-477b-b11f-c44bf97a5402)

![Capture2](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/ea792b74-df4b-4a7b-8503-6b9ed33a58b6)

![Capture3](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/dee6680b-5510-48b2-b0cd-6dfa1c1d869b)
![double](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/8daa31a7-a4d8-49b6-bd8f-8ab35542cea0)

**Comment by skreza** [comment]
I'm also seeing this exact same issue since 28th Dec.
Agree with @davidsonimagerygmailcom that it's likely an issue on the SEMS portal side, maybe they need to configure NTP on their servers?

Unfortunately I can't see a way to use an automation to disable the SEMS service for a period of time, as that would have been a quick workaround within HA. Only other thing I can thing of as a workaround for now is to create a new template sensor in HA that copies the value of the original sensor from this integration and stop this sensor from updating between 00:00 - 00:15, you would then have to add this sensor to the energy dashboard for it to reflect correctly. Hardly ideal but would achieve the desired outcome!

Any help from @TimSoethout would be greatly appreciated!

**Comment by davidsonimagerygmailcom** [comment]
As a workaround I've done a few things, as yet I am not 100% sure if it's sorted it (and its only a bandaid).

So the issue as ew know is the double dip ... the import kwh and export kwh all go to zero around midnight, then dip back to the preivous days usages before again going to zero (all of which is data coming from Sems Portal, yet doens't show up in the reports you can run from it).    SemsPortal accounting bug of some sort which came in as soon as they fixed the bigger bug which was KWH metrics weren't resetting at all (for days, even on semsportal).

So the issue is HA seeing that zero'ing, followed by data - and thinks its new usage (hooray for generating power from the moon right??).

I did initially try using an automation that does a Utlility meter reset (as pictured below) ... but even so the "consumed" power would still show (and util meter calibrate doesnt apply to that).

So I went a step further and actually turned off the recorder from 11.59pm to 1230am, my idea being not recording any energy data at all therefore it disregards what it sees.

If this doesnt work, another idea I had was I might just disallow HA from being able to talk to the internet between midniht ad 1230 ... so it never gets exposed to this garbage double dip (it's back to zero by 1215 usually).

I reckon Goodwe have a bug in their system which started around Christmas Eve ... they've "fixed" it by zero'ing values a second time instead of fixing the original fault (maybe unwittingly), and it doesn't affect the data they present to users so probably don' care too much for what HA is pulling from them via API. 

**I've not yet confirmed if this actually works (before anyone goes following down this line).**

![2024-01-02_13-45-03](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/af06920a-e1ef-4957-923b-8216fcf5c956)
![2024-01-02_13-49-51](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/f4d6547f-80e3-40ee-8234-f78b72f64b78)
![2024-01-02_13-49-26](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/bed1cd59-655a-4778-931b-6333d6effe0a)

![2024-01-02_13-50-06](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/d88685ad-4f3f-40af-bd30-e72d0829cc4f)

**Comment by skreza** [comment]
Thanks for the update @davidsonimagerygmailcom

I've come up with a similar workaround for now and will update tomorrow if it has helped.
Essentially I've disabled update polling on the integration itself and setup an automation to update the entities every minute between 00:15:00 through to 00:00:30 which hopefully gets the 0kWh at midnight but skips everything between 12:01AM to 12:15AM

YAML for the automation below, you must have disabled polling on the integration first (Open integration, click 3 dot menu, system options, turn off 'Enable polling for updates') Also untested so don't do this if you're unsure, I'll provide an update tomorrow advising if I had any luck with this or not.

Automation is triggered every minute to update the entities in the list. You'll need to change these to match your entity ids, I just added all entities associated with the integration.

`alias: GoodWe SEMS Portal Polling
description: ""
trigger:
  - platform: time_pattern
    seconds: "00"
condition:
  - condition: time
    after: "00:15:00"
    before: "00:00:30"
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - sensor.homekit_xyz
        - sensor.homekit_xyz_export
        - sensor.homekit_xyz_import
        - sensor.inverter_xyz
        - sensor.inverter_xyz_energy
mode: single`

**Comment by davidsonimagerygmailcom** [comment]
You could even apply the logic of missing the first zero'ing entirely (as you'll get it after 1215 anyway) ... kinda why I went for 1159pm (bypass the whole shemozzle)

**Comment by skreza** [comment]
I wasn't sure if it needed to reset to zero at midnight for the energy dashboard to calculate it correctly.
Assuming it doesn't then absolutely the condition could be changed to 12:15am through to 11:59pm
```
condition:
  - condition: time
    after: "00:15:00"
    before: "23:59:00"
```

**Comment by davidsonimagerygmailcom** [comment]
Just to add spanner to the works, I notice the first zero'ing was about 00:01:22 ... then 00:02:24 back up to 10.5kwh ... 00:06:02 back to 0kwh

The kwh readings aren't the same either so not sure what's going on back end.

![Uploading 2024-01-02_14-16-42.jpg…]()

**Comment by davidsonimagerygmailcom** [comment]
> I wasn't sure if it needed to reset to zero at midnight for the energy dashboard to calculate it correctly. Assuming it doesn't, then absolutely the condition could be changed to 12:15am through to 11:59pm
> 
> ```
> condition:
>   - condition: time
>     after: "00:15:00"
>     before: "23:59:00"
> ```

Good point.   Not sure!

**Comment by davidsonimagerygmailcom** [comment]
> alias: GoodWe SEMS Portal Polling
> description: ""
> trigger:
>   - platform: time_pattern
>     seconds: "00"
> condition:
>   - condition: time
>     after: "00:15:00"
>     before: "00:00:30"
> action:
>   - service: homeassistant.update_entity
>     data: {}
>     target:
>       entity_id:
>         - sensor.homekit_xyz
>         - sensor.homekit_xyz_export
>         - sensor.homekit_xyz_import
>         - sensor.inverter_xyz
>         - sensor.inverter_xyz_energy
> mode: single

Where / how do you define your YAMl code? is it on the Automation itself, or into a file and then calling it somehow?
![2024-01-02_14-28-37](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/a3424785-a176-4f82-bdfb-7674e1195fe8)

**Comment by skreza** [comment]
Create a new automation as normal, then press three dots in top right and select Edit in YAML.
Paste the code replacing anything already visible and then change it back to Edit in visual editor from that top menu again.

**Comment by davidsonimagerygmailcom** [comment]
How would we define every 30 seconds for polling instead of minute? 

I wonder if ;

trigger:
  - platform: time_pattern
    seconds: "00"
    seconds: "30"

is permissible

(please excuse my amateurism!)

**Comment by skreza** [comment]
Ok, so based on the fact that we don't really know when the data will spike after zeroing the first time and that the first zeroing may not be exactly at midnight I've modified things slightly and added a second automation. The first automation is same as above however I've removed the condition so it'll run every minute no matter what. The second automation will trigger when the entity hits 0, it will then disable the first automation wait fifteen minutes and then enable it again. This way we don't have to worry about exact timing from the SEMS side.

**Automation 1**
```
alias: GoodWe SEMS Portal Polling
description: ""
trigger:
  - platform: time_pattern
    seconds: "00"
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - sensor.homekit_xyz
        - sensor.homekit_xyz_export
        - sensor.homekit_xyz_import
        - sensor.inverter_xyz
        - sensor.inverter_xyz_energy
mode: single
```

**Automation 2**
```
alias: GoodWe SEMS Portal Polling Controller
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.homekit_xyz_export
    to: "0"
condition: []
action:
  - service: automation.turn_off
    target:
      entity_id: automation.goodwe_sems_portal_polling
    data:
      stop_actions: true
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    target:
      entity_id: automation.goodwe_sems_portal_polling
    data: {}
mode: single
```

**Comment by skreza** [comment]
Re 30 second polling, you would just need a second action, one covers 00 seconds the other covers 30 seconds.
```
trigger:
  - platform: time_pattern
    seconds: "00"
  - platform: time_pattern
    seconds: "30"
```

**Comment by davidsonimagerygmailcom** [comment]
Done and working well, i might just to go straight to using your method and see what happens tonight (it's 3pm here).

**Comment by micheldejongh** [comment]
Another option: 

trigger:
  - platform: time_pattern
    seconds: /30

**Comment by davidsonimagerygmailcom** [comment]
Skreza's workaround worked perfectly

Stopped polling a bit before midnight... oblivious to the double dipping being done at Goodwe's Cloud , and then at 1220 polls again to observe a zero and move on

![2024-01-03_7-49-57](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/87551b44-be22-4557-a016-476f080f6356)

**Comment by skreza** [comment]
Glad to hear it worked @davidsonimagerygmailcom Now I need to figure out why it didn't work for me! Hahaha.
Did you end up making it time based entirely or did you use the last method I posted which looked for 0 kWh and then disabled the polling automation for 15 minutes?
I tried this way and it did hit 0 however it didn't seem to trigger that automation for some reason, last triggered should be around 12 hours ago not 19! Hmmmm
![image](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/13235835/1b57ad0a-0626-4392-976c-0f3bff718831)

**Comment by davidsonimagerygmailcom** [comment]
Hey Mate, I just went with your first solution ... the simple one.  
It just polls all day long (every 30 seconds), except betweeen 23:59 and 00:20 ... worked a treat.

![2024-01-03_11-30-02](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/b4c18230-6729-4d03-b1e1-38a63de59aca)
![2024-01-03_11-29-50](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/036a7516-9985-4b22-a3ce-d53f3f0dcc04)
![2024-01-03_11-29-28](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/fccc6989-8acd-4996-a34a-df618dff3b2c)
![2024-01-03_11-32-46](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/d02a6270-4593-47e4-a977-0a0c7ae359ed)

**Comment by skreza** [comment]
Thanks for that, I might have made it more complex than it needed to be haha!
Reverted it back to time based with the condition, hopefully all good tonight!

**Comment by davidsonimagerygmailcom** [comment]
Fingers Crossed!
All crusing along on my side.  I guess ew won't actually know if the double dip gets fixed until we go back to polling during 2359 > 0020hrs

![2024-01-03_12-36-20](https://github.com/TimSoethout/goodwe-sems-home-assistant/assets/116411962/8c639396-cccb-4ee0-b290-2cb100efcea0)

**Comment by justinmaiuto** [comment]
Just found this one, seems similar issue (possibly the same?)

https://github.com/home-assistant/core/issues/106677

**Comment by TimSoethout** [comment]
Hi all, great that you've found a workaround. I'm currently limited in time and energy to work on this, but I'm happy to merge a fix if someone provides it. :)

**Comment by davidsonimagerygmailcom** [comment]
> Just found this one, seems similar issue (possibly the same?)
> 
> [home-assistant/core#106677](https://github.com/home-assistant/core/issues/106677)


Yeeepp that's what first caught my eye ... I was perplexed how I'd made so much power from the Moon, and who was running around pulling huge loads at midnight :)

**Comment by skreza** [comment]
Ok went back to my original suggestion and worked perfectly last night.

So for those looking for a workaround, the YAML code below works well, create a new automation and use this, make sure you change the sensors in the entity_id list to match your sensors. You also need to disable polling on the 'GoodWe SEMS PV API' integration (Open integration, click 3 dot menu, system options, turn off 'Enable polling for updates')

```
alias: GoodWe SEMS Portal Polling
description: ""
trigger:
  - platform: time_pattern
    seconds: "00"
condition:
  - condition: time
    after: "00:20:00"
    before: "23:59:00"
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - sensor.homekit_xyz
        - sensor.homekit_xyz_export
        - sensor.homekit_xyz_import
        - sensor.inverter_xyz
        - sensor.inverter_xyz_energy
mode: single
```
